/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageDashboards: typeof import('./src/components/PageDashboards.vue')['default']
    PageDocument: typeof import('./src/components/PageDocument.vue')['default']
    PageHome: typeof import('./src/components/PageHome.vue')['default']
    PageInterfaces: typeof import('./src/components/PageInterfaces.vue')['default']
    PageTempAPI: typeof import('./src/components/PageTempAPI.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
