/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dashboards: typeof import('./src/components/Dashboards.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Interfaces: typeof import('./src/components/Interfaces.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PageDashboards: typeof import('./src/components/PageDashboards.vue')['default']
    PageHome: typeof import('./src/components/PageHome.vue')['default']
    PageInterfaces: typeof import('./src/components/PageInterfaces.vue')['default']
    PageNavigation: typeof import('./src/components/PageNavigation.vue')['default']
    PageViewing: typeof import('./src/components/PageViewing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Viewing: typeof import('./src/components/Viewing.vue')['default']
  }
}
