// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-02-12T07:52:46.270Z

export const BUILD_INFO = {
    buildTime: '2026-02-12T07:52:46.270Z',
    gitCommit: 'c8b0686',
    gitBranch: '25-Transform-ReqIF-to-PIG',
    gitDirty: false
};
