// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-02-12T16:29:56.269Z

export const BUILD_INFO = {
    buildTime: '2026-02-12T16:29:56.269Z',
    gitCommit: '339dc77',
    gitBranch: '50-html-loader',
    gitDirty: false
};
