// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-02-17T15:16:22.546Z

export const BUILD_INFO = {
    buildTime: '2026-02-17T15:16:22.546Z',
    gitCommit: 'd7d270f',
    gitBranch: '25-Transform-ReqIF-to-PIG',
    gitDirty: false
};
