// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-03-27T22:36:29.194Z

export const BUILD_INFO = {
    // from package.json:
    appName: 'CASCaRA-App',
    appVersion: '0.1.0',
    // from Git:
    buildTime: '2026-03-27T22:36:29.194Z',
    gitCommit: 'unknown',
    gitBranch: 'unknown',
    gitDirty: false
};
