// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-05-19T12:56:36.225Z

export const BUILD_INFO = {
    // from package.json:
    appName: 'CASCaRA-App',
    appVersion: '0.2.3',
    // from Git:
    buildTime: '2026-05-19T12:56:36.225Z',
    gitCommit: 'f4ebb19',
    gitBranch: '27-transform-cascara-to-json-ld',
    gitDirty: false
};
