// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-03-06T13:03:27.052Z

export const BUILD_INFO = {
    // from package.json:
    appName: 'CASCaRA-App',
    appVersion: '0.1.0',
    // from Git:
    buildTime: '2026-03-06T13:03:27.052Z',
    gitCommit: '69c2ecc',
    gitBranch: '55-transform-pig-to-html',
    gitDirty: false
};
