// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-05-13T06:40:46.061Z

export const BUILD_INFO = {
    // from package.json:
    appName: 'CASCaRA-App',
    appVersion: '0.2.0',
    // from Git:
    buildTime: '2026-05-13T06:40:46.061Z',
    gitCommit: '0e8d44f',
    gitBranch: '79-rename-all-namespaces-pig-to-cas',
    gitDirty: false
};
