// Auto-generated by scripts/generate-build-info.js - DO NOT EDIT
// Generated at: 2026-08-12T13:54:23.901Z

export const BUILD_INFO = {
    // from package.json:
    appName: 'CASCaRA-Validation-Tool',
    appVersion: '0.2.9',
    // from Git:
    buildTime: '2026-08-12T13:54:23.901Z',
    gitCommit: 'b877162',
    gitBranch: '101-render-the-document-outline-with-collapsible-folders-per-tree',
    gitDirty: false
};
